inherit_gem:
  theforeman-rubocop:
    - default.yml

Layout/LineLength:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/foreman_wreckingball/engine.rb'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/foreman_wreckingball/hosts_controller.rb'
    - 'app/services/foreman_wreckingball/vmware_hypervisor_importer.rb'
    - 'lib/foreman_wreckingball/engine.rb'
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - Rakefile

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*

Rails/ApplicationRecord:
  Exclude:
    - db/**/*
