language: ruby
cache:
  - npm
  - bundler
install:
  - unset BUNDLE_GEMFILE
  - cd ..
  - git clone https://github.com/theforeman/foreman.git -b ${FOREMAN_CORE_BRANCH} --depth 1
  - git clone https://github.com/theforeman/foreman-tasks.git -b ${FOREMAN_TASKS_BRANCH} --depth 1
  - cd ${FOREMAN_PLUGIN_NAME}
  - bundle install --jobs=3 --retry=3
  - npm install eslint
  - cd ../foreman
  - echo "gemspec :path => '../${FOREMAN_PLUGIN_NAME}'" > bundler.d/${FOREMAN_PLUGIN_NAME}.local.rb
  - echo "gem 'foreman-tasks-core', :path => '../foreman-tasks'" > bundler.d/foreman-tasks.local.rb
  - echo "gem 'foreman-tasks', :path => '../foreman-tasks'" >> bundler.d/foreman-tasks.local.rb
  - ln -s settings.yaml.test config/settings.yaml
  - ln -s database.yml.example config/database.yml
  - bundle install --jobs=3 --retry=3 --without journald development postgresql mysql2 console journald
  - npm install
  - bundle exec rake webpack:compile
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - cd ../${FOREMAN_PLUGIN_NAME}
  - bundle exec rubocop
  - node ./node_modules/.bin/eslint . app/**/*.js
  - cd ../foreman
  - bundle exec rake test:${FOREMAN_PLUGIN_NAME}
  - bundle exec rake "plugin:assets:precompile[${FOREMAN_PLUGIN_NAME}]" RAILS_ENV=production
  - bundle exec rake test TEST="test/unit/foreman/access_permissions_test.rb"
env:
  global:
    - TESTOPTS=-v
    - FOREMAN_PLUGIN_NAME=foreman_wreckingball
jobs:
  include:
  - rvm: 2.5
    env:
      - FOREMAN_CORE_BRANCH=develop
      - FOREMAN_TASKS_BRANCH='master'
  - rvm: 2.3
    env:
      - FOREMAN_CORE_BRANCH=1.24-stable
      - FOREMAN_TASKS_BRANCH='0.17.x'
addons:
  apt:
    packages:
    - nodejs
    - git
    - libsqlite3-dev
    - zlib1g-dev
    - libvirt-dev
